server:
  port: 8081
  servlet:
    jsp:
      init-parameters:
        development: true

spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: c##tracker
    password: 1234
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

mybatis:
  config-location: classpath:mybatis-config.xml
  configuration:
    map-underscore-to-camel-case: true